# Generated by Django 3.2.8 on 2022-02-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAppComInd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='Comunidad',
            new_name='user',
        ),
    ]
